### ISSUE TITLE
[1.17.1] [Crash] Disabling steel tools prevents loading old worlds

### ISSUE THREAD

**Issue by ruvaldak** [kwpugh/EmeraldTools#11]
Disabling steel tools prevents loading worlds that were created with steel tools enabled. This doesn't effect any other tool type that I know of, but might be worth investigating. The crash is as follows:

```15:13:23] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Item: emerald_tools:steel_ingot does not exist
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.14) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069) ~[?:?]
	at net.minecraft.client.MinecraftClient.createIntegratedResourceManager(MinecraftClient:2153) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1999) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1939) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.start(TitleScreen:3616) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.mdeaa49a$lambda$drawMenuButton$2$5(TitleScreen:3580) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen:311) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:190) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1140) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Item: emerald_tools:steel_ingot does not exist
	at net.minecraft.recipe.CookingRecipeSerializer.method_17879(CookingRecipeSerializer:33) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.recipe.CookingRecipeSerializer.read(CookingRecipeSerializer:33) ~[?:?]
	at net.minecraft.recipe.CookingRecipeSerializer.read(CookingRecipeSerializer:11) ~[?:?]
	at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager:123) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:54) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
	at net.minecraft.client.MinecraftClient.createIntegratedResourceManager(MinecraftClient:2152) ~[?:?]
	... 37 more
```

**Comment by kwpugh** [comment]
fixed in. latest update.

**Comment by ruvaldak** [comment]
This still occurs on version 1.2.24 from Curseforge. 

```[07:51:44] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Item: emerald_tools:steel_ingot does not exist
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.14) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069) ~[?:?]
	at net.minecraft.client.MinecraftClient.createIntegratedResourceManager(MinecraftClient:2153) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1999) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1939) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.start(TitleScreen:3616) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.md4f470c$lambda$drawMenuButton$2$5(TitleScreen:3580) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.mouseClicked(TitleScreen:311) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:190) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1140) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Item: emerald_tools:steel_ingot does not exist
	at net.minecraft.recipe.CookingRecipeSerializer.method_17879(CookingRecipeSerializer:33) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.recipe.CookingRecipeSerializer.read(CookingRecipeSerializer:33) ~[?:?]
	at net.minecraft.recipe.CookingRecipeSerializer.read(CookingRecipeSerializer:11) ~[?:?]
	at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager:123) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:54) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:71) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
	at net.minecraft.client.MinecraftClient.createIntegratedResourceManager(MinecraftClient:2152) ~[?:?]
	... 37 more```

**Comment by kwpugh** [comment]
hmmm, I tested this on my server and it was fine.  Odd.

**Comment by kwpugh** [comment]
can you post a link to the entire crash report?

**Comment by ruvaldak** [comment]
Just did some testing, and can confirm, this only happens when disabling Steel set and attempting to load a world that had them enabled. Every other set loads fine. MC doesn't crash, it just complains about the datapack being corrupted or whatever and refuses to load the world.

[latest.log](https://github.com/kwpugh/EmeraldTools/files/6885237/latest.log)

![image](https://user-images.githubusercontent.com/15901769/127151750-1ed18b09-11d9-4dfd-acd4-dc08681306fd.png)

**Comment by kwpugh** [comment]
[EmeraldTools-Fabric-1.17.1-1.2.25.jar.zip](https://github.com/kwpugh/EmeraldTools/files/6885289/EmeraldTools-Fabric-1.17.1-1.2.25.jar.zip)

Try this version real quick and see if it works.

**Comment by ruvaldak** [comment]
> [EmeraldTools-Fabric-1.17.1-1.2.25.jar.zip](https://github.com/kwpugh/EmeraldTools/files/6885289/EmeraldTools-Fabric-1.17.1-1.2.25.jar.zip)
> 
> Try this version real quick and see if it works.

Still occurs.

**Comment by ruvaldak** [comment]
[general.json5.zip](https://github.com/kwpugh/EmeraldTools/files/6885341/general.json5.zip)

This is my config.

**Comment by kwpugh** [comment]
so is the same config settings the same on client and server?

**Comment by kwpugh** [comment]
[EmeraldTools-Fabric-1.17.1-1.2.25.jar.zip](https://github.com/kwpugh/EmeraldTools/files/6885547/EmeraldTools-Fabric-1.17.1-1.2.25.jar.zip)

another change, try this one.

**Comment by kwpugh** [comment]
Please post a link to your:
- launcher log
- server system log

I'm having trouble narrowing this down without seeing the full story

**Comment by ruvaldak** [comment]
> [EmeraldTools-Fabric-1.17.1-1.2.25.jar.zip](https://github.com/kwpugh/EmeraldTools/files/6885547/EmeraldTools-Fabric-1.17.1-1.2.25.jar.zip)
> 
> another change, try this one.

This jar worked fine, loaded the world without issue. 

> so is the same config settings the same on client and server?

This is all on an SSP world so yes.

**Comment by ruvaldak** [comment]
```[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_helmet removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_chestplate removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_shovel removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_boots removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_ingot_from_blasting removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_ingot removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_axe removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_ingot_from_smelting removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_leggings removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_hoe removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: the_aether:mossy_holystone removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_block_to_ingot removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_block_from_ingot removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_sword removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_pickaxe removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_helmet removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_chestplate removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_shovel removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_boots removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_ingot_from_blasting removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_ingot removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_axe removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_ingot_from_smelting removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_leggings removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_hoe removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: the_aether:mossy_holystone removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_block_to_ingot removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_block_from_ingot removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_sword removed now.
[09:08:25] [Server thread/ERROR]: Tried to load unrecognized recipe: emerald_tools:steel_pickaxe removed now.
```


This was in the logs when loading. The world loaded without crashing, no issues visible.

**Comment by kwpugh** [comment]
Good.  I was guessing it was an invalid forge tag that was still in there.

Fabric has no way to surprise the invalid recipes warnings when items are disabled.  They should not cause any issues though.
