### ISSUE TITLE
Crash when launching fabric server

### ISSUE THREAD

**Issue by Angular-Angel** [kwpugh/EmeraldTools#13]
I made a little modpack for pre-release 5, and it works fine for the client, but not for the server:

```Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[14:59:05] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft 1.18-pre5
[14:59:06] [main/INFO]: Loading for game Minecraft 1.18-pre5
[14:59:06] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[14:59:06] [main/INFO]: Loading 43 mods:
	- cloth-basic-math 0.6.0
	- cloth-config 6.0.42
	- emerald_tools 1.3.23
	- fabric 0.42.8+1.18
	- fabric-api-base 0.4.1+b4f4f6cd6d
	- fabric-api-lookup-api-v1 1.3.5+3ac43d956d
	- fabric-biome-api-v1 6.0.1+3ac43d956d
	- fabric-command-api-v1 1.1.6+3ac43d956d
	- fabric-commands-v0 0.2.5+b4f4f6cd6d
	- fabric-containers-v0 0.1.17+3ac43d956d
	- fabric-content-registries-v0 0.3.5+3ac43d956d
	- fabric-crash-report-info-v1 0.1.8+3ac43d956d
	- fabric-dimensions-v1 2.1.7+43d295716d
	- fabric-entity-events-v1 1.3.5+3ac43d956d
	- fabric-events-interaction-v0 0.4.15+3ac43d956d
	- fabric-events-lifecycle-v0 0.2.5+b4f4f6cd6d
	- fabric-game-rule-api-v1 1.0.10+3ac43d956d
	- fabric-item-api-v1 1.2.7+3ac43d956d
	- fabric-item-groups-v0 0.3.3+3ac43d956d
	- fabric-lifecycle-events-v1 1.4.10+c15ca3356d
	- fabric-loot-tables-v1 1.0.8+3ac43d956d
	- fabric-mining-level-api-v1 1.0.3+3ac43d956d
	- fabric-mining-levels-v0 0.1.6+b4f4f6cd6d
	- fabric-networking-api-v1 1.0.18+3ac43d956d
	- fabric-networking-v0 0.3.5+b4f4f6cd6d
	- fabric-object-builder-api-v1 1.10.12+3ac43d956d
	- fabric-object-builders-v0 0.7.6+3ac43d956d
	- fabric-particles-v1 0.2.9+526dc1ac6d
	- fabric-registry-sync-v0 0.8.5+3ac43d956d
	- fabric-rendering-data-attachment-v1 0.2.3+3ac43d956d
	- fabric-rendering-fluids-v1 0.1.18+3ac43d956d
	- fabric-resource-loader-v0 0.4.11+3ac43d956d
	- fabric-screen-handler-api-v1 1.1.11+3ac43d956d
	- fabric-structure-api-v1 2.0.7+03d159cf6d
	- fabric-tag-extensions-v0 1.2.5+3ac43d956d
	- fabric-tool-attribute-api-v1 1.3.3+3ac43d956d
	- fabric-transfer-api-v1 1.5.4+b4f4f6cd6d
	- fabricloader 0.12.5
	- fallingtree 2.14.3
	- incantationem 1.1.2+1.18-pre1
	- java 17
	- minecraft 1.18-beta.5
	- pugh_tools 1.1.10
[14:59:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/angle/Documents/Games/Minecraft/Pre-Release-Server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:62)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:100)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:74)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72)
	... 2 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config emerald_tools.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:87)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	... 7 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 13 more
```

**Comment by Angular-Angel** [comment]
Apparently this is from: https://discord.com/channels/507304429255393322/535180192960872458/910360386442760254

**Comment by kwpugh** [comment]
yeah, the mod is not updated to pre5 yet.

**Comment by kwpugh** [comment]
should be fixed with latest release

**Comment by kwpugh** [comment]
If you have any more issues, let me know.
