### ISSUE TITLE
[1.19] Minecraft crashes on startup with EmeraldTools-Fabric-1.19.1-1.4.22

### ISSUE THREAD

**Issue by mpustovoi** [kwpugh/EmeraldTools#32]
Hi
When starting Minecraft with EmeraldTools-Fabric-1.19.1-1.4.22, I see this

```
[main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: com.kwpugh.pugh_tools.Tools.Excavator: method 'void <init>(net.minecraft.class_1832, float, float, net.minecraft.class_1792$class_1793 )' not found
at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: com.kwpugh.pugh_tools.Tools.Excavator: method 'void <init>(net.minecraft.class_1832, float, float, net.minecraft.class_1792$class_1793)' not found
at com.kwpugh.emerald_tools.items.areatools.ModExcavator.<init>(ModExcavator.java:18)
at com.kwpugh.emerald_tools.init.ItemInit.<clinit>(ItemInit.java:55)
at net.minecraft.item.ArmorItem.handler$bge000$emeraldToolsConstructor(ArmorItem:540)
at net.minecraft.item.ArmorItem.<init>(ArmorItem:95)
at net.minecraft.item.Items.<clinit>(Items:769)
at net.minecraft.item.Item.fromBlock(Item:74)
at net.minecraft.block.Block.asItem(Block:554)
at net.minecraft.class_7143$class_7144.method_41583(class_7143.java:60)
at net.minecraft.class_7143$class_7144.method_41581(class_7143.java:66)
at net.minecraft.class_7143.method_41579(class_7143.java:199)
at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98)
at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105)
at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104)
at net.minecraft.util.registry.Registry.<clinit>(Registry:326)
at net.minecraft.Bootstrap.initialize(Bootstrap:50)
at net.minecraft.client.main.Main.main(Main:154)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
... 2 more
```

If I remove EmeraldTools-Fabric-1.19.1-1.4.22 Minecraft starts up fine. I understand that your mod has received 2 updates since version 1.4.22, but I can't upgrade from 1.19 to 1.19.2 right now due to other mods.

**Comment by kwpugh** [comment]
I'm no longer supporting that version.

**Comment by mpustovoi** [comment]
Ok I got it
